	;;; generated by ../../BootSetup/BootSetup.rb (2016-04-17 13:24:23 +0200)

;;; ========================================================================
;;; Interrupt Table
;;; ========================================================================

	.org  0                   	
	rjmp  RESET               	
	reti                      	; INT0
	reti                      	; PCINT0
	reti                      	; Timer1 Compare A
	reti                      	; Timer1 Overflow
	reti                      	; Timer0 Overflow
	reti                      	; EEPROM Ready
	reti                      	; Analog Compare
	reti                      	; Analog Conversion
	reti                      	; Timer1 Compare B
	reti                      	; Timer0 Compare A
	reti                      	; Timer0 Compare B
	reti                      	; WATCHDOG
	reti                      	; USI Start
	reti                      	; USI Overflow

;;; ========================================================================
;;; Boot Setup
;;; ========================================================================

RESET:	ldi   r16, 0x00           	; 0
	out   0x0d, r16           	; USICR - USI Control Register
	out   0x0e, r16           	; USISR - USI Status Register
	out   0x17, r16           	; DDRB - Port B Data Direction Register
	out   0x18, r16           	; PORTB - Port B Data Register
	ldi   r17, 0x0f           	; 15
	out   0x20, r17           	; PRR - Power Reduction Register
	ldi   r17, 0x20           	; 32
	out   0x35, r17           	; MCUCR - MCU Control Register
	out   0x3b, r16           	; GIMSK - General Interrupt Mask Register

	ldi   r17, 0x80           	
	out   0x26, r17           	; CLKPR - Clock Prescale Register
	ldi   r17, 0x00           	
	out   0x26, r17           	; CLKPR - Clock Prescale Register

	ldi   r17, lo8(0x015f)    	; RAM End
	out   0x3d, r17           	; SPL - Stack Pointer Low
	ldi   r17, hi8(0x015f)    	; RAM End
	out   0x3e, r17           	; SPH - Stack Pointer High
	out   0x3f, r16           	; SREG - Status Register

	rjmp  Main                	
