	;;; generated by ../../BootSetup/BootSetup.rb (2016-04-17 16:35:05 +0200)

;;; ========================================================================
;;; Interrupt Table
;;; ========================================================================

	.org  0                   	
	rjmp  RESET               	
	nop                       	
	reti                      	; INT0
	nop                       	
	reti                      	; INT1
	nop                       	
	reti                      	; PCINT0
	nop                       	
	reti                      	; PCINT1
	nop                       	
	reti                      	; PCINT2
	nop                       	
	reti                      	; WATCHDOG
	nop                       	
	reti                      	; Timer2 Compare A
	nop                       	
	reti                      	; Timer2 Compare B
	nop                       	
	reti                      	; Timer2 Overflow
	nop                       	
	reti                      	; Timer1 Capture
	nop                       	
	reti                      	; Timer1 Compare A
	nop                       	
	reti                      	; Timer1 Compare B
	nop                       	
	reti                      	; Timer1 Overflow
	nop                       	
	reti                      	; Timer0 Compare A
	nop                       	
	reti                      	; Timer0 Compare B
	nop                       	
	reti                      	; Timer0 Overflow
	nop                       	
	reti                      	; SPI
	nop                       	
	reti                      	; USART RX Complete
	nop                       	
	reti                      	; USART UDR Empty
	nop                       	
	reti                      	; USART TX Complete
	nop                       	
	reti                      	; ADC Conversion Complete
	nop                       	
	reti                      	; EEPROM Ready
	nop                       	
	reti                      	; Analog Compare
	nop                       	
	reti                      	; 2-wire Serial Interface
	nop                       	
	reti                      	; Store Program Memory Ready
	nop                       	

;;; ========================================================================
;;; Boot Setup
;;; ========================================================================

RESET:	ldi   r16, 0x00           	; 0
	out   0x04, r16           	; DDRB - Port B Data Direction Register
	out   0x05, r16           	; PORTB - Port B Data Register
	out   0x07, r16           	; DDRC - Port C Data Direction Register
	out   0x08, r16           	; PORTC - Port C Data Register
	out   0x0a, r16           	; DDRD - Port D Data Direction Register
	out   0x0b, r16           	; PORTD - Port D Data Register
	out   0x1d, r16           	; EIMSK - External Interrupt Mask Register
	out   0x2c, r16           	; SPCR - SPI Control Register
	out   0x2d, r16           	; SPSR - SPI Status Register
	ldi   r17, 0x01           	; 1
	out   0x33, r17           	; SMCR - Sleep Mode Control Register
	out   0x35, r16           	; MCUCR - MCU Control Register
	ldi   r17, 0xef           	; 239
	sts   0x64, r17           	; PRR - Power Reduction Register
	sts   0x69, r16           	; EICRA - External Interrupt Control Register A
	sts   0xb8, r16           	; TWBR - TWI Bit Rate Register
	sts   0xb9, r16           	; TWSR - TWI Status Register
	ldi   r17, 0xfe           	; 254
	sts   0xba, r17           	; TWAR - TWI (Slave) Address Register
	sts   0xbc, r16           	; TWCR - TWI Control Register
	sts   0xbd, r16           	; TWAMR - TWI (Slave) Address Mask Register
	sts   0xc0, r16           	; UCSR0A - USART Control and Status Register 0 A
	sts   0xc1, r16           	; UCSR0B - USART Control and Status Register 0 B
	ldi   r17, 0x06           	; 6
	sts   0xc2, r17           	; UCSR0C - USART Control and Status Register 0 C
	sts   0xc4, r16           	; UBRR0L - USART Baud Rate Register Low
	sts   0xc5, r16           	; UBRR0H - USART Baud Rate Register High

	ldi   r17, 0x01           	
	out   0x35, r17           	; MCUCR - MCU Control Register
	ldi   r17, 0x00           	
	out   0x35, r17           	; MCUCR - MCU Control Register

	ldi   r17, 0x80           	
	sts   0x61, r17           	; CLKPR - Clock Prescale Register
	ldi   r17, 0x00           	
	sts   0x61, r17           	; CLKPR - Clock Prescale Register

	ldi   r17, lo8(0x08ff)    	; RAM End
	out   0x3d, r17           	; SPL - Stack Pointer Low
	ldi   r17, hi8(0x08ff)    	; RAM End
	out   0x3e, r17           	; SPH - Stack Pointer High
	out   0x3f, r16           	; SREG - Status Register

	rjmp  Main                	
