;;; generated by ../../BootSetup/BootSetup.rb (2016-04-23 15:42:22 +0200)

	.include "ports.ATtiny45.inc"	

;;; ========================================================================
;;; Interrupt Table
;;; ========================================================================

	.org  0                   	
	rjmp  RESET               	
	reti                      	; INT0
	reti                      	; PCINT0
	reti                      	; Timer1 Compare A
	reti                      	; Timer1 Overflow
	reti                      	; Timer0 Overflow
	reti                      	; EEPROM Ready
	reti                      	; Analog Compare
	reti                      	; Analog Conversion
	reti                      	; Timer1 Compare B
	reti                      	; Timer0 Compare A
	reti                      	; Timer0 Compare B
	reti                      	; WATCHDOG
	reti                      	; USI Start
	reti                      	; USI Overflow

;;; ========================================================================
;;; Boot Setup
;;; ========================================================================

RESET:	ldi   r16, 0x00           	; 0
	out   USICR, r16          	; USI Control Register [0x0d]
	out   USISR, r16          	; USI Status Register [0x0e]
	out   DDRB, r16           	; Port B Data Direction Register [0x17]
	out   PORTB, r16          	; Port B Data Register [0x18]
	ldi   r17, 0x0f           	; 15
	out   PRR, r17            	; Power Reduction Register [0x20]
	ldi   r17, 0x20           	; 32
	out   MCUCR, r17          	; MCU Control Register [0x35]
	out   GIMSK, r16          	; General Interrupt Mask Register [0x3b]

	ldi   r17, 0x80           	
	out   CLKPR, r17          	; Clock Prescale Register [0x26]
	ldi   r17, 0x00           	
	out   CLKPR, r17          	; Clock Prescale Register [0x26]

	ldi   r17, lo8(RAMEND)    	
	out   SPL, r17            	; Stack Pointer Low [0x3d]
	ldi   r17, hi8(RAMEND)    	
	out   SPH, r17            	; Stack Pointer High [0x3e]
	out   SREG, r16           	; Status Register [0x3f]

	rjmp  Main                	
